import Layout from "@/components/Layout"
import Head from "next/head"
import Image from "next/image"
import profilePic from "../../public/images/profile/developer-pic-1.png"
import AnimatedText from "@/components/AnimatedText"
import Link from "next/link"
import { LinkArrow } from "@/components/icons"

export default function Home() {
  return (
    <>
      <Head>
        <title>Gene&apos;s Portfolio</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="flex items-center text-dark w-full min-h-screen">
        <Layout className="pt-0">
          <div className="flex items-center justify-between w-full">
            <div className="w-1/2">
              <Image
                src={profilePic}
                alt="Gene Howell"
                className="w-full h-auto"
              />
            </div>
            <div className="w-1/2 flex flex-col items-center self-center">
              <AnimatedText
                text="Hello there! I'm Gene, your personal Digital Media
                Specialist"
                className="!text-4xl !text-left animate-fade-in-down"
              />
              <p className="my-4 text-base font-medium">
                From the very beginning, my journey in the realm of technology
                began with web development. However, as I progressed through
                college, my horizons expanded, and I discovered my deep-seated
                passion for programming, graphic design, video production, and
                radio.
              </p>
              <p className="my-4 text-base font-medium">
                Today, I bring together my diverse expertise to create
                captivating digital experiences that seamlessly integrate the
                worlds of web development, programming, graphic design, video
                production, and radio. Welcome to my portfolio site, where you
                can explore the culmination of my multifaceted skills and
                projects.
              </p>
              <div className="flex items-center self-start mt-2">
                <Link
                  href="/Resume.pdf"
                  className="flex items-center bg-dark text-light p-2.5 px-6 rounded-lg text-lg font-semibold hover:bg-light hover:text-dark border-2 border-solid border-transparent hover:border-dark"
                  download={true}
                >
                  Resume
                  <LinkArrow className="w-6 ml-1" />
                </Link>
                <Link
                  href="mailto:genehowell9@gmail.com"
                  className="ml-4 text-lg font-medium capitalize text-dark underline"
                >
                  Contact Me
                </Link>
              </div>
            </div>
          </div>
        </Layout>
      </main>
    </>
  )
}
