import Head from "next/head"

export default function Home() {
  return (
    <>
      <Head>
        <title>Gene&apos;s Portfolio</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="">Main Content</main>
    </>
  )
}
